# Generated by Django 3.0 on 2022-05-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordersid', models.IntegerField()),
                ('addtime', models.DateField(null=True)),
                ('yhname', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'detail',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastestype', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('yhname', models.CharField(max_length=50, null=True)),
                ('hsyname', models.CharField(max_length=50, null=True)),
                ('status', models.IntegerField(default=4)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Sorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastesname', models.CharField(max_length=200)),
                ('wastestype', models.CharField(max_length=50)),
                ('numbers', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sort',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(default='匿名', max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('sex', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('authority', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Wastes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waid', models.IntegerField(default=11)),
                ('wastestype', models.CharField(max_length=50)),
                ('price', models.FloatField()),
            ],
            options={
                'db_table': 'waste',
            },
        ),
    ]
